apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: lbl-k8s-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP 
  selector:
    name: lbl-k8s-mysql
  type: LoadBalancer
